### PR TITLE
Added user not found feature

### LINKED ISSUE #19: When we enter a username that does not exist, the application does not display anything which is quite vague.
**Describe the bug**
When we enter a username that does not exist, the application does not display anything which is quite vague. What is to be done is as follows:
- Display a vector image of error or anything suitable as it is present on the landing page.
- Display the text "Username does not exist." below or beside the image.

You can use _conditional rendering_ of react to display the above things.

### PR DESCRIPTION
**Pull request by AltCtrlDel1999**
Fixes #19  
Description:
   Bug resolved for displaying the user not found information if the given username is incorrect.
Changes:
   Appropriate changes made in the Profile component in src/component Directory.

### CODE REVIEW

**Comment by AltCtrlDel1999** [comment]
**Test:**
Tested on my local machine
x-special/nautilus-clipboard
copy
file:///home/shubham/Documents/ss19

**Comment by AltCtrlDel1999** [comment]
**Test:**
   Tested on Local machine
Screenshot from 2020-08-15 00-03-13

**Review by garimasingh128 — CHANGES_REQUESTED** [review]
Looks good! You can decrease the size I think looks a little overpowering!

**Comment by AltCtrlDel1999** [comment]
Requested changes 

- [x] image size decreased

- [x] testing done on local machine

Screenshot from 2020-08-15 14-24-50

**Comment by AltCtrlDel1999** [comment]
Hey, any update regarding changes and merging?

**Comment by garimasingh128** [comment]
Yup. need to have a discussion with the mentors. Feel free to solve and create other issues.

**Comment by AltCtrlDel1999** [comment]
@garimasingh128 Any updates?

**Comment by garimasingh128** [comment]
@ShauryaBhandari can u please review this?

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
@AltCtrlDel1999 Please change the branch to hakincodes, we are not accepting any PRs to the master branch. 
Otherwise looks good, we will merge it.

**Comment by garimasingh128** [comment]
@AltCtrlDel1999 can u resolve the conflicts in Profile.js? Then I will merge this.

**Comment by AltCtrlDel1999** [comment]
@garimasingh128 Conflicts resolved. Now you can merge it

**Comment by garimasingh128** [comment]
@AltCtrlDel1999  Please put the not-found svg in the images folder here: https://github.com/garimasingh128/gitsetgo/blob/hakincodes/src/components/images

**Pull request merged**
