### PR TITLE
Added Table to Display Repositories

### LINKED ISSUE #21: About displaying of  Repository
In created resume the repository are displaying in single.. column  in place of that we can put in table form then it will look more good.

### PR DESCRIPTION
**Pull request by aliana17**
# Description
added table displaying the serial number, language of the project and repository name.
Fixes #21 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

image

### CODE REVIEW

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
@anchal7299  Please add some description about your PR along with a screenshot if possible. I will then merge it.

**Comment by aliana17** [comment]
I updated my comment, Please have a look.

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
Could you please add some custom styling to the table? It looks really unappealing rn. @anchal7299

**Comment by garimasingh128** [comment]
@anchal7299 There are some conflicts. Pls, resolve them. Also, post the new screenshots of the changes u have made.

**Comment by aliana17** [comment]
I resolved all conflicts. 
Here is the screenshots of changes
image

**Comment by garimasingh128** [comment]
Looks okay as of now. Good

**Pull request merged**
