### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by tanishq98**
# Description

Dockerize the gitsetgo application issue 

Fixes # 15

## Type of change
Added a new Dockerfile 

# How Has This Been Tested?
Ran the Dockerfile using containers. It successfully built the image and ran the container on local host 3000

**Test Configuration**:
*Docker: v-19.03.12

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by garimasingh128** [comment]
Make the PR to the hackincodes branch.

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
Please shift your PR to the hakincodes branch.

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
@tanishq98  Have you made this same PR as #46 to the hakincodes branch?

**Comment by tanishq98** [comment]
@ShauryaBhandari  Yes. That's the same PR on HackinCodes branch.

**Comment by ShauryaBhandari** [comment]
Cool @tanishq98. I will then be closing this one and putting that one on for further review.
For future reference, you can change the branch on an already open pull request easily, there is no need to open a new one.

**Pull request closed without merging**
