### PR TITLE
Displaying repositories through table

### LINKED ISSUE #21: About displaying of  Repository
In created resume the repository are displaying in single.. column  in place of that we can put in table form then it will look more good.

### PR DESCRIPTION
**Pull request by aliana17**
# Description

added table displaying the serial number, language of the project and repository name.  
Fixes #21 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

displaying repo through table

### CODE REVIEW

**Comment by garimasingh128** [comment]
looks good. will review later. move on to next one

**Comment by aliana17** [comment]
Okay

**Review by ShauryaBhandari — APPROVED** [review]
Ignore this.

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
Please shift PR to hakincodes branch. And make all future PRs to it.

**Comment by aliana17** [comment]
> Please shift PR to hakincodes branch. And make all future PRs to it.

okay

**Comment by garimasingh128** [comment]
> Please shift PR to hakincodes branch. And make all future PRs to it.

@anchal7299 ??

**Pull request closed without merging**
