### PR TITLE
added turven

### LINKED ISSUE #47: Add turven to the site.
turven lets people on your website see how many other people are also reading the same page 👀

Link: https://github.com/maximevaillancourt/turven

### PR DESCRIPTION
**Pull request by mharshita**
# Description
I have added turven.

Fixes #47 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
Please make all PRs to hakincodes branch.

**Comment by garimasingh128** [comment]
> Please make all PRs to hakincodes branch.

@mharshita ??

**Comment by mharshita** [comment]
@garimasingh128 @ShauryaBhandari  Sorry but i dont know how to shift to another branch.

**Comment by garimasingh128** [comment]
There's an edit option near the title of your PR on the top of this screen. Do that from there. Or google it simply.

**Comment by mharshita** [comment]
@garimasingh128  Done!

**Comment by garimasingh128** [comment]
Conflicting files
public/index.html

Please do a pull and resolve these.

**Comment by mharshita** [comment]
@garimasingh128  I have done it. Please review. and also sorry for the delay.

**Pull request merged**
