### PR TITLE
Adding pictures of Fork and Clone#33

### LINKED ISSUE #33: Adding pictures of Fork and Clone
**Is your feature request related to a problem? Please describe.**
As a beginner to GitHub,
1. People might not be able to find the fork and clone buttons. 
2. The Setup guidelines doesn't mention to fork the project which is necessary to create a pull request and thus can be confusing.

**Describe the solution you'd like**
1. I think it would be nice if pictures could be added to depict how to setup the project locally. Eg: Arrows pointing to Fork and Clone buttons
2. Adding a step to Fork the project in 'Steps to setup development environment' part of the README.

### PR DESCRIPTION
**Pull request by madhhuurrii**
# Added images and content 

Fixes #33 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by madhhuurrii** [comment]
@garimasingh128 please review my PR

**Comment by garimasingh128** [comment]
I will. Please move on to the next issue or create one.

**Comment by garimasingh128** [comment]
@madhhuurrii pls change the base branch to hackincodes!

**Comment by madhhuurrii** [comment]
Ok

**Comment by madhhuurrii** [comment]
@garimasingh128 done.

**Comment by garimasingh128** [comment]
```
Conflicting files
README.md
```

Please do a git pull and resolve this conflict!

**Pull request closed without merging**
