### PR TITLE
Added Policy Page

### PR DESCRIPTION
**Pull request by asi309**
# Description

Added a privacy policy page as mentioned in issue #91 . Added BrowserRouter for navigation with Link to the privacy page in the footer. This addition does not break any previous functionality as locally tested

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by asi309** [comment]
Any changes?

**Comment by garimasingh128** [comment]
Can you please pull changes from hackincodes branch as that's the branch we're working on. And add these changes to that branch's code only. Also change the base branch of pr to hackincodes. The content looks good.

**Comment by asi309** [comment]
Let me know if that's okay @garimasingh128

**Comment by asi309** [comment]
Any changes?

**Comment by garimasingh128** [comment]
It shows privacy policy file was deleted. did u change anything?

**Comment by asi309** [comment]
No I did not. But if there's an issue, I can always open a new PR

**Review by asi309 — COMMENTED** [review]
Check this commit please @garimasingh128

**Comment by garimasingh128** [comment]
I am checking the last commit. Can u close this one and open a new PR?

**Pull request closed without merging**
