### PR TITLE
FooterComponent

### LINKED ISSUE #20: change the design of footer
As of now, the footer looks quite simple and plain. Design and implement a new footer with other important information. You can take inspiration from other websites and re-design it.

### PR DESCRIPTION
**Pull request by srishtij2000**
# Description

Added a new component Footer.js

Fixes #20 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by srishtij2000** [comment]
](https://user-images.githubusercontent.com/64734684/90425636-b490bc80-e0dd-11ea-8c47-8eea5d592a04.png)

**Comment by srishtij2000** [comment]
I have made another design of footer . So should I make the pull request for the same also?

**Comment by garimasingh128** [comment]
Let me review this one then we will see. Till then attach some screenshots or videos of both the designs.

**Comment by srishtij2000** [comment]
Okay I will

**Comment by srishtij2000** [comment]
footer1
One footer idea

**Comment by srishtij2000** [comment]
footer2
Second footer idea

**Comment by srishtij2000** [comment]
footer2

**Comment by srishtij2000** [comment]
footer2
Second footer idea

**Comment by srishtij2000** [comment]
Kindly suggest any changes that I should do in the footer

**Comment by garimasingh128** [comment]
The first one looks better but decrease the height a lil bit. Also make a list of the links that you'll need like Disclaimer, FAQ, Home and all. We will provide those and create issues for the ones that haven't been made yet.

**Comment by srishtij2000** [comment]
Okay will update the PR with the following changes

**Comment by srishtij2000** [comment]
I have made the changes so kindly review them and kindly tell whatever changes that I need to make

**Comment by garimasingh128** [comment]
Cool! Move on to the next issue.

**Comment by srishtij2000** [comment]
okay

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
Please change the branch to hakincodes @srishtij2000

**Comment by srishtij2000** [comment]
Okay I will do

**Comment by srishtij2000** [comment]
Actually my laptop isn't working from so many days so I am not able to change the branch . I will do it like in 4-5 days positively.

**Comment by garimasingh128** [comment]
you can do it from ur phone also.

**Comment by srishtij2000** [comment]
I have changed the branch is it fine now?

**Comment by garimasingh128** [comment]
Yesh but now there are some conflicts.

```
Conflicting files
public/index.html
src/components/Header.js
```

Take your time and resolve those.

**Comment by srishtij2000** [comment]
Okay okay I will do it

**Comment by srishtij2000** [comment]
I have made the changes . Is it okay now?

**Comment by garimasingh128** [comment]
@ShauryaBhandari  can u test this one?

**Comment by srishtij2000** [comment]
Is it okay or I need to make some changes?

**Comment by garimasingh128** [comment]
According to me, it looks good! Can you attach a final screenshot of the output how it looks?

**Comment by srishtij2000** [comment]
It looks like this

**Comment by garimasingh128** [comment]
Please remove faq,. Contact and about as these have no backlinks. From the resources, remove everything except privacy policy. Add a quick "about" two lines below home in the first column.

**Comment by srishtij2000** [comment]
footernew
Is it fine now?

**Comment by garimasingh128** [comment]
Keep the About at the same place as earlier. 
Instead add a contact portion where you have written about now in the first column
Remove blog also

**Comment by srishtij2000** [comment]
footer
Do I need to add email and a phone number also or is it fine?

**Comment by garimasingh128** [comment]
Yeah it looks fine as of now. Keep it like this only.

**Comment by srishtij2000** [comment]
So I should make the changes in the PR?

**Comment by srishtij2000** [comment]
Could you please tell me that whether I should make the changes or not?

**Comment by garimasingh128** [comment]
Ya make the changes. @ShauryaBhandari if you have any suggestions then welcome.

> footer
> Do I need to add email and a phone number also or is it fine?

This one is the final footer.

**Comment by ShauryaBhandari** [comment]
Yes!
So:
1) the github image looks really bad, maybe we can include a white svg, rather an image. Just an outline, something classy. 
2) center the copyright line. 
3) the social media icons look too small and ignored on the right, maybe bring them to the left, increase the size. 
These changes will make it look better.

**Comment by srishtij2000** [comment]
Okay okay I will make the changes

**Comment by srishtij2000** [comment]
nee
I have made the changes so please kindly review

**Comment by ShauryaBhandari** [comment]
Please bring the links at one single level. 
Also, put the copyright after a line break, it is at same level as social icons.

**Comment by srishtij2000** [comment]
What links are you talking about?

**Comment by srishtij2000** [comment]
nn
These are the changes that I have done. Is it fine?

**Comment by ShauryaBhandari** [comment]
Looks fine to me! I hope it is responsive as well.

**Review by ShauryaBhandari — APPROVED** [review]
Approved.

**Comment by srishtij2000** [comment]
Okay I will make the changes in PR

**Comment by garimasingh128** [comment]
@ShauryaBhandari please create separate issues for "Privacy policy" page and Contact us page and link them to the footer. Also add the Hacktoberfest label to them.

**Comment by ShauryaBhandari** [comment]
Done @garimasingh128 , please let me know incase you want any changes in it.

**Comment by srishtij2000** [comment]
I haven't made changes in the PR so I guess you have merged the previous one not the new one

**Comment by garimasingh128** [comment]
@srishtij2000 My bad, I didn't noticed it. I have reverted that. Can you create a separate PR now. 
@ShauryaBhandari It looks good. I'll give the details once someone takes them up.

**Comment by srishtij2000** [comment]
Okay I will create a separate PR

**Comment by srishtij2000** [comment]
I have created a new PR so kindly review it

**Pull request merged**
