### PR TITLE
Add fork and clone buttons pics to fix issue #33

### LINKED ISSUE #33: Adding pictures of Fork and Clone
**Is your feature request related to a problem? Please describe.**
As a beginner to GitHub,
1. People might not be able to find the fork and clone buttons. 
2. The Setup guidelines doesn't mention to fork the project which is necessary to create a pull request and thus can be confusing.

**Describe the solution you'd like**
1. I think it would be nice if pictures could be added to depict how to setup the project locally. Eg: Arrows pointing to Fork and Clone buttons
2. Adding a step to Fork the project in 'Steps to setup development environment' part of the README.

### PR DESCRIPTION
**Pull request by sanchibansal340**
# Description

Added the fork and clone buttons pictures. Changed the description of 'Setting up the Development Environment' to include 'fork the repo'.

Fixes  #33 

## Type of change

- [x] This change requires a documentation update

# How Has This Been Tested?

Tested this on StackEdit

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
Most of it looks good, just a few changes:
- Please remove the emojis before the "A github profile resume generator"
- Resize the screenshots, they appear to be too huge in the preview

**Comment by sanchibansal340** [comment]
The emojis weren't part of the issue but I will do that. I will check what I can do about the size of screenshots.
Thanks!

**Comment by sanchibansal340** [comment]
@ShauryaBhandari I made the required changes, please review. Thanks!

**Comment by ShauryaBhandari** [comment]
@sanchibansal340 , Please shift your PR to the hakincodes branch. 
And make all future PRs to the hakincodes branch. 
NOTE: you can change the branch of this existing PR without closing this

**Review by ShauryaBhandari — APPROVED** [review]
Approved.

**Comment by garimasingh128** [comment]
@sanchibansal340 
- You can write separate guidelines for general participants and for hackincodes participants to create PRs on develop and hackincodes branch respectively
- You should also write a small description of how to create a PR. Like the steps to add and commit and then going to the browser to create a PR and change the base branch if needed.

**Review by garimasingh128 — APPROVED** [review]

**Pull request merged**
