### PR TITLE
Changed PDF file name #83

### LINKED ISSUE #83: Changing PDF file name for the resume
As of now, the generated PDF file has the name "github_resume" which sounds vague and odd. Change the file name to "Username_Github_Resume". 
```
For ex: Garima Singh_Github_Resume.
```

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
# Description

Changed the generating PDF file name from resume_github.pdf to Username_Github_Resume.pdf 

Fixes #83 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I run the project and generated the pdf of my profile resume and the format was as asked by the project admin.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

# Screenshot
githubbbb

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey @garimasingh128 I've done the required changes . Kindly review them..

**Comment by garimasingh128** [comment]
Looks good. Make the base branch to hackincodes.

**Comment by kritikaparmar-programmer** [comment]
Hey @garimasingh128 how to do that I've no idea..

**Comment by garimasingh128** [comment]
https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by kritikaparmar-programmer** [comment]
Done @garimasingh128  👍

**Pull request merged**
