### PR TITLE
Made links clickable(hyperlink) in the generated resume(NOT PDF)

### LINKED ISSUE #34: Making the remaining links Clickable(Hyperlink) in the generated Resume(NOT PDF) and changing color of hyperlinks.
**Is your feature request related to a problem? Please describe.**
1. In the Generated Resume(NOT PDF) Blog and Github profile links are not hyperlink.
2. Hyperlinks are not differently colored.

**Describe the solution you'd like**
1. Adding anchor tags to the mentioned links
2. Changing the color of anchor tags in CSS

### PR DESCRIPTION
**Pull request by kaushiksriram16**
# Description
1. Added anchor tags to the Github profile,Blog links in the generated resume.
2. Changed the color of all the hyperlinks.
Fixes #34 

## Type of change

-  New feature (non-breaking change which adds functionality)

# Checklist:

-  My code follows the style guidelines of this project
-  I have performed a self-review of my own code
-  My changes generate no new warnings
-  New and existing unit tests pass locally with my changes
-  Any dependent changes have been merged and published in downstream modules

Here's the glimpse of changes I made:
git2

### CODE REVIEW

**Comment by garimasingh128** [comment]
Cool. move on the next one.

**Comment by kaushiksriram16** [comment]
> Cool. move on the next one.

Thank you! @garimasingh128

**Comment by garimasingh128** [comment]
@kaushiksriram16 pls change the base branch to hackincodes.

**Comment by kaushiksriram16** [comment]
> @kaushiksriram16 pls change the base branch to hackincodes.

Done!

**Comment by garimasingh128** [comment]
Conflicting files
src/components/css/style.css

Please resolve them by doing a git pull.

**Comment by kaushiksriram16** [comment]
> Conflicting files
> src/components/css/style.css
> 
> Please resolve them by doing a git pull.

I didn't get it.

**Comment by kaushiksriram16** [comment]
@garimasingh128  I think I resolved it check it once.

**Pull request merged**
