### PR TITLE
README updation

### LINKED ISSUE #80: Updating broken links in readme file.
There are several instances in the README where the URL of the project is incorrect. Correct it and replace it with https://github.com/garimasingh128/gitsetgo

### PR DESCRIPTION
**Pull request by ritvij14**
# Description

I have updated the broken links of the images that were shown as a part of the documentation as to how to contribute to this project.
Fixes #80 (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by ritvij14** [comment]
@garimasingh128 I have made the changes you asked, please have a look.

**Comment by garimasingh128** [comment]
Close the PRs which don't need to be reviewed. Also don't create different prs for every change. You can simply add ur code and pr is updated automatically.

**Comment by ritvij14** [comment]
@garimasingh128 this is the only PR I have made:sweat_smile: 
The other one is made by someone else.

**Comment by garimasingh128** [comment]
Oh I'm so sorry. It's too much confusion sometimes. Apologies. I'll review it.

**Review by ShauryaBhandari — APPROVED** [review]
Approved by me. @garimasingh128 Please just go through the images once, to be sure. Looks fine to me.

**Pull request merged**
