### PR TITLE
Fixed unnecessary white space above profile picture in mobile view

### LINKED ISSUE #89: Unnecessary white space.
There is a lot of unneeded white space above the profile picture in the resume, when viewed on mobile mode, needs minor fixing.

### PR DESCRIPTION
**Pull request by ritvij14**
# Description
There was a big marginTop set above the left region which was making the unnecessary whitespace above the profile picture.

Fixes #89 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [ ] Test A
image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ritvij14** [comment]
@ShauryaBhandari I have removed the `marginTop` that was causing the excessive whitespace. Does this work?

**Comment by ShauryaBhandari** [comment]
@ritvij14  yes fine, I hope you tested it in all screen sizes, hope nothing is breaking.

**Review by ShauryaBhandari — APPROVED** [review]
Approved.

**Comment by ritvij14** [comment]
@ShauryaBhandari thanks for the approval and yes, I have checked all screen sizes :+1:

**Pull request merged**
