### PR TITLE
Improved Responsiveness

### LINKED ISSUE #24: The design in the mobile frame is not responsive in some places.
The design in the mobile frame is not responsive in some areas. Also, when you click on Go ahead in mobile, it doesn't generates a resume and goes to the github repo due to click on the "fork me on github" ribbon. Make the website responsive and make changes to make it look good on all devices.

### PR DESCRIPTION
**Pull request by Saicharan67**
Fixes #24

## Improved Responsiveness By Replacing fork me on GitHub ribbon with another one 

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

-I have Checked the app in various mobile frames and it's good in all

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Saicharan67** [comment]
Screenshot (71)

**Comment by Saicharan67** [comment]
There is an issue for changing themes, so I didn't add toggle button for changing themes

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
Looks fine @Saicharan67 , but please shift your PR to the hakincodes for it to be merged.

**Comment by Saicharan67** [comment]
I didn't understand?!.

**Comment by Saicharan67** [comment]
I have changed the base branch to hakincodes pls review it

**Review by ShauryaBhandari — CHANGES_REQUESTED** [review]
@Saicharan67  It has some conflicts with index.html, please review them once.

**Comment by Saicharan67** [comment]
I have solved it

**Pull request merged**
